-- ============================================================
-- tables.sql
-- Description: All tables for Prescription Fraud System
-- ============================================================

-- =========================
-- Patient Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'PATIENT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE patient (
                patient_id NUMBER PRIMARY KEY,
                full_name  VARCHAR2(100) NOT NULL,
                dob        DATE,
                gender     CHAR(1)
            )';
    END IF;
END;
/

-- =========================
-- Doctor Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'DOCTOR';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE doctor (
                doctor_id NUMBER PRIMARY KEY,
                full_name VARCHAR2(100) NOT NULL,
                specialty VARCHAR2(50)
            )';
    END IF;
END;
/

-- =========================
-- Pharmacy Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'PHARMACY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE pharmacy (
                pharmacy_id NUMBER PRIMARY KEY,
                pharmacy_name VARCHAR2(100) NOT NULL,
                address VARCHAR2(200)
            )';
    END IF;
END;
/

-- =========================
-- Prescription Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'PRESCRIPTION';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE prescription (
                prescription_id NUMBER PRIMARY KEY,
                patient_id      NUMBER NOT NULL,
                doctor_id       NUMBER NOT NULL,
                pharmacy_id     NUMBER NOT NULL,
                issue_date      DATE DEFAULT SYSDATE,
                valid_until     DATE,
                total_items     NUMBER DEFAULT 0,
                notes           VARCHAR2(4000),
                status          VARCHAR2(20) DEFAULT ''ISSUED'',
                CONSTRAINT fk_presc_patient FOREIGN KEY (patient_id) REFERENCES patient(patient_id),
                CONSTRAINT fk_presc_doctor FOREIGN KEY (doctor_id) REFERENCES doctor(doctor_id),
                CONSTRAINT fk_presc_pharmacy FOREIGN KEY (pharmacy_id) REFERENCES pharmacy(pharmacy_id)
            )';
    END IF;
END;
/

-- =========================
-- Prescription Item Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'PRESCRIPTION_ITEM';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE prescription_item (
                presc_item_id   NUMBER PRIMARY KEY,
                prescription_id NUMBER NOT NULL,
                drug_name       VARCHAR2(100) NOT NULL,
                dosage          VARCHAR2(50),
                quantity        NUMBER,
                unit            VARCHAR2(20),
                instructions    VARCHAR2(4000),
                CONSTRAINT fk_item_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(prescription_id)
            )';
    END IF;
END;
/

-- =========================
-- Fraud Alert Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'FRAUD_ALERT';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE fraud_alert (
                fraud_alert_id NUMBER PRIMARY KEY,
                prescription_id NUMBER NOT NULL,
                alert_type      VARCHAR2(50),
                severity        VARCHAR2(20),
                description     VARCHAR2(4000),
                fraud_flag      CHAR(1) DEFAULT ''N'',
                action_date     DATE DEFAULT SYSDATE,
                CONSTRAINT fk_alert_prescription FOREIGN KEY (prescription_id) REFERENCES prescription(prescription_id)
            )';
    END IF;
END;
/

-- =========================
-- System Audit Trail Table
-- =========================
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tables
    WHERE table_name = 'SYSTEM_AUDIT_TRAIL';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE '
            CREATE TABLE system_audit_trail (
                audit_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_name       VARCHAR2(50),
                action_type     VARCHAR2(50),
                table_name      VARCHAR2(50),
                record_id       NUMBER,
                action_timestamp TIMESTAMP DEFAULT SYSTIMESTAMP,
                status          VARCHAR2(20),
                fraud_flag      CHAR(1) DEFAULT ''N'',
                old_values      VARCHAR2(4000),
                new_values      VARCHAR2(4000)
            )';
    END IF;
END;
/
